name: IAC CI & CD

on:
  push:
    branches:
      - main
      - feat1234
    paths:
      - "iac/**"
      - ".github/workflows/iac.workflow.yml"

env:
  ACTIONS_RUNNER_DEBUG: true

defaults:
  run:
    working-directory: iac

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Generate parameters file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.55.0
          inlineScript: |
            az bicep install
            az bicep version
            az bicep build-params --file iac/prd.bicepparam

      - name: Deploy
        uses: azure/CLI@v1
        env:
          RG_NAME: "famous-speeches"
          LOCATION: "australiaeast"
          ENV: prd
        with:
          azcliversion: 2.55.0
          inlineScript: |
            az group create --name ${{env.RG_NAME}} --location ${{env.LOCATION}}
            az deployment group create --name fmsp${{ENV}} --resource-group ${{env.RG_NAME}} --template-file iac/main.bicep --parameters iac/${{ENV}}.json

      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: data
          container_name: srcdata
          connection_string: https://stfmspprd.blob.core.windows.net/
          extra_args: "--pattern *.pdf"
          overwrite: "false"
